#
# linux/drivers/devices/Makefile
#
ifdef CONFIG_MTD_MT_SYMPHONY_SPI_FLASH
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += symphony_spi.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_spi_nor.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_winbond.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_spansion.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_eon.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_sst.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_esmt.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_gigadevice.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_issi.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_dosilicon.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_macronix.o
obj-$(CONFIG_MTD_MT_SYMPHONY_SPI_FLASH)  += concerto_spi_nand.o
endif

ifdef CONFIG_MTD_MT_CONCERTO_SPI_FLASH
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_spi.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_spi_nor.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_winbond.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_spansion.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_eon.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_sst.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_esmt.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_gigadevice.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_issi.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_dosilicon.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_macronix.o
obj-$(CONFIG_MTD_MT_CONCERTO_SPI_FLASH)  += concerto_spi_nand.o
endif