export WIFIAUDIO_MONTAGE=y
#export WIFIAUDIO_MTK=y

include $(TOPDIR)/rules.mk

PKG_NAME:=opus_demo
PKG_RELEASE:=1

PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/nls.mk

define Package/opus_demo
	SECTION:=sound
	CATEGORY:=Sound
        TITLE:= creat http playlist
        VERSION:=1
      DEPENDS:= +libopus
endef

define Package/opus_demo/description
  creat http playlist
endef


TARGET_CFLAGS += \
	-I$(STAGING_DIR)/usr/include \

TARGET_LDFLAGS += -Wl,-gc-sections  \
  -Wl,-rpath-link=$(STAGING_DIR)/usr/lib -lcdb


#LDFLAGS="$(TARGET_LDFLAGS) -L$(STAGING_DIR)/usr/lib -Wl,-rpath-link=$(STAGING_DIR)/usr/lib" \
TARGET_LDFLAGS += -Wl,-rpath-link=$(STAGING_DIR)/usr/lib  -lopus

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
	$(CP) ./src/* $(PKG_BUILD_DIR)/
	$(call TSYNC,$(PKG_BUILD_DIR))
endef

TARGET_LDFLAGS += -lm
#LIBS:= -ljson-c -ldl

define Package/opus_demo/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(CP) $(PKG_BUILD_DIR)/opus_demo $(1)/usr/bin
	
endef

$(eval $(call BuildPackage,opus_demo))
