
.PHONY:	all install clean
install:
	cp -rf css ${INSTALL_DIR}/www/
	cp -rf js ${INSTALL_DIR}/www/
	cp xzx.html ${INSTALL_DIR}/www/
	chmod 644 ${INSTALL_DIR}/www/xzx.html
	chmod 644 ${INSTALL_DIR}/www/js/function.js
	chmod 644 ${INSTALL_DIR}/www/css/stylesheet.css

