#ifndef __WIFIAUDIO_UCICONFIG_H__
#define __WIFIAUDIO_UCICONFIG_H__

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef WIFIAUDIO_DEBUG	
#define WIFIAUDIO_CONFIG_PATH "/usr/local/openwrt_lib/etc/conf/"
#else
#define WIFIAUDIO_CONFIG_PATH "/etc/conf/"
#endif

#ifdef WIFIAUDIO_DEBUG
#include <uci.h>
#else
#include <wdk/cdb.h>

typedef enum {
	WIFIAUDIO_UCI_PARAMETER_AUDIONAME=0,
	WIFIAUDIO_UCI_PARAMETER_AP_SSID1,
	WIFIAUDIO_UCI_PARAMETER_AUDIODETECTSTATUS,
	WIFIAUDIO_UCI_PARAMETER_AUDIONAMESTATUS,
	WIFIAUDIO_UCI_PARAMETER_AMAZON_LOGINSTATUS,
	WIFIAUDIO_UCI_PARAMETER_AMAZON_PRODUCTID,
	WIFIAUDIO_UCI_PARAMETER_AMAZON_DSN,
	WIFIAUDIO_UCI_PARAMETER_AMAZON_CODECHALLENGE,
	WIFIAUDIO_UCI_PARAMETER_AMAZON_CODECHALLENGEMETHOD,
	WIFIAUDIO_UCI_PARAMETER_AMAZON_LANGUAGE,
	WIFIAUDIO_UCI_PARAMETER_AMAZON_AUTHORIZATIONCODE,
	WIFIAUDIO_UCI_PARAMETER_AMAZON_REDIRECTURI,
	WIFIAUDIO_UCI_PARAMETER_AMAZON_CLIENTID,
	WIFIAUDIO_UCI_PARAMETER_BT_UPDATE_FLAGE,
	WIFIAUDIO_UCI_PARAMETER_BTCONNECTSTATUS,
	WIFIAUDIO_UCI_PARAMETER_CURRENT_TITLE,
	WIFIAUDIO_UCI_PARAMETER_CURRENT_ARTIST,
	WIFIAUDIO_UCI_PARAMETER_CURRENT_CONTENTURL,
	WIFIAUDIO_UCI_PARAMETER_CURRENT_COVERURL,
	WIFIAUDIO_UCI_PARAMETER_CURRENT_ALBUM,
	WIFIAUDIO_UCI_PARAMETER_CHARGE,
	WIFIAUDIO_UCI_PARAMETER_CHANNEL,
	WIFIAUDIO_UCI_PARAMETER_FUNCTION_SUPPORT,
	WIFIAUDIO_UCI_PARAMETER_FIRMWARE,
	WIFIAUDIO_UCI_PARAMETER_IP,
	WIFIAUDIO_UCI_PARAMETER_KEY_NUM,
	WIFIAUDIO_UCI_PARAMETER_LAN_IP,
	WIFIAUDIO_UCI_PARAMETER_LANGUAGE,
	WIFIAUDIO_UCI_PARAMETER_LANGUAGE_SUPPORT,
	WIFIAUDIO_UCI_PARAMETER_MAC_ADDR,
	WIFIAUDIO_UCI_PARAMETER_MANUFACTURER,
	WIFIAUDIO_UCI_PARAMETER_MANUFACTURER_URL,
	WIFIAUDIO_UCI_PARAMETER_MODEL_DESCRIPTION,
	WIFIAUDIO_UCI_PARAMETER_MODEL_NAME,
	WIFIAUDIO_UCI_PARAMETER_MODEL_NUMBER,
	WIFIAUDIO_UCI_PARAMETER_MODEL_URL,
	WIFIAUDIO_UCI_PARAMETER_PROJECT,
	WIFIAUDIO_UCI_PARAMETER_POWER,
	WIFIAUDIO_UCI_PARAMETER_PLAYMODE,
	WIFIAUDIO_UCI_PARAMETER_POWOFF_ENABLE,
	WIFIAUDIO_UCI_PARAMETER_POWOFF_GETTIME,
	WIFIAUDIO_UCI_PARAMETER_WIFICONNECTSTATUS,
	WIFIAUDIO_UCI_PARAMETER_RELEASE,
	WIFIAUDIO_UCI_PARAMETER_SW_VER,
	WIFIAUDIO_UCI_PARAMETER_SPEECH_RECOGNITION,
	WIFIAUDIO_UCI_PARAMETER_SERVER_CONEX_VER,
	WIFIAUDIO_UCI_PARAMETER_SET_TIMEZONE,
	WIFIAUDIO_UCI_PARAMETER_TF_STATUS,
	WIFIAUDIO_UCI_PARAMETER_TESTMODE,
	WIFIAUDIO_UCI_PARAMETER_USB_STATUS,
	WIFIAUDIO_UCI_PARAMETER_VOLUME,
	WIFIAUDIO_UCI_PARAMETER_WIFIAUDIO_UUID,
	WIFIAUDIO_UCI_PARAMETER_WIFI_UPDATE_FLAGE,
	WIFIAUDIO_UCI_PARAMETER_NONE
} WIFIAudio_UciConfig_Parameter;

#define WIFIAUDIO_UCICONFIG_PARAMETER_BUFFSIZE	100
#endif

extern int WIFIAudio_UciConfig_FreeValueString(char **ppstring);
extern char * WIFIAudio_UciConfig_SearchValueString(char *psearch);
extern int WIFIAudio_UciConfig_SearchAndSetValueString(char *psearch, char *pstring);
extern int WIFIAudio_UciConfig_SetValueString(char *psearch, char *pstring);

#ifdef __cplusplus
}
#endif

#endif
