#
# Copyright (C) 2014 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=wavplayer
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/kernel.mk

define Package/wavplayer
	SECTION:=utils
	CATEGORY:=Utilities
  TITLE:=uartd
  DEPENDS:= +alsa-lib +libcchip +libpthread +librt
endef

define Package/wavplayer/description
  wav player
endef

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
	$(CP) ./src/* $(PKG_BUILD_DIR)/
endef

TARGET_CFLAGS += 

define Package/wavplayer/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/wavplayer $(1)/usr/bin/
	
endef

$(eval $(call BuildPackage,wavplayer))
