var _msgTable_cn = {
	/* msg at wdk(start) */
	" seconds": " 秒",
	"Continue": "继续",
	"Error": "储存错误",
	"Login timeout ! Please login again !": "登入逾时 ! 请重新登入 !",
	"OK": "确定",
	"Please click 'Continue' button again!": "请再按'继续'按纽!",
	"Processing! Please wait ": "处理中，请等待 ",
	"Rebooting! Please wait ": "系统重启中，请等待 ",
	"Success": "储存成功",
	"The settings are not changed!!": "设定没变!!",
	"Your browser does not support AJAX!": "你所用的浏览器并不支援AJAX!",
	"not exist": "不存在",
	/* msg at wdk(end) */
	/*--ifdef CONFIG_SONIX_MOTION_DETECTION--*/
	"Motion Detection": "移动侦测",
	"Record Time Limit": "纪录时间限制",
	"Record to SD card": "记录到SD卡",
	"Snapshot Time Limit": "快照时间限制",
	"Snapshot times": "快照次数",
	"Snapshot to SD card": "快照到SD卡",
	"deselect a range": "取消选择范围",
	"locked": "锁定",
	"select a range": "选择范围",
	"times per second": "次/秒",
	"unlocked": "解锁",
	/*--endif--*/
	/*--ifdef CONFIG_SONIX_OSD--*/
	"2nd string": "第二行字串",
	"Black": "黑色",
	"Blue": "蓝色",
	"Font Color": "字型颜色",
	"Font Size": "字型大小",
	"Green": "绿色",
	"Red": "红色",
	"Start Position": "起始位置",
	"White": "白色",
	"background": "背景",
	"column": "列",
	"foreground": "前景",
	"row": "行",
	"whitespace": "空白",
	/*--endif--*/
	/*--ifdef CONFIG_WEBCAM_IMAGE_PARAMETERS--*/
	"Backlight Compensation": "背光补偿",
	"Bitrate": "比特率",
	"Brightness": "亮度",
	"CBR": "固定码率",
	"Contrast": "对比",
	"Custom": "自订",
	"Exposure Mode": "曝光模式",
	"Exposure Time": "曝光时间",
	"Exposure, Auto Priority": "自动曝光优先",
	"Flip": "翻转",
	"Gain": "增益",
	"Gamma": "伽玛值",
	"High": "高",
	"Hue": "色调",
	"Image Parameters": "图片参数",
	"Low": "低",
	"Middle": "中",
	"Mirror": "镜像",
	"Power Line Frequency": "电力线频率",
	"Quality": "质量",
	"Quantization Parameter": "量化参数",
	"Saturation": "饱和",
	"Sharpness": "锐利度",
	"VBR": "可变码率",
	"White Balance Temperature Mode, Auto": "自动白平衡色温模式",
	"White Balance Temperature": "白平衡色温",
	/*--endif--*/
	/*--ifdef CONFIG_PACKAGE_webcam_streamer--*/
	"2-way audio": "双向音频",
	"Audio Device": "音频装置",
	"FPS divisor": "画面更新率除数",
	"Loop Recording": "循环录影",
	"Maximum Time of File": "档案纪录最大时间",
	"On-Screen Display": "屏幕显示",
	"RTP Server will restart after system time synchronization": "系统时间同步之后,将重新启动FTP伺服器",
	"RTP Streaming": "串流",
	"Record Settings": "纪录设定",
	"Samba Upload": "SAMBA上传",
	"Schedule": "排程",
	"Server Settings": "伺服器设定",
	"Snapshot": "快照",
	"Streaming": "串流",
	"Video&Audio Settings": "视频与音频设定",
	"Webcam": "摄像头",
	/*--endif--*/
	/*--ifdef CONFIG_PACKAGE_webcam_streamer_CAREVOLTAGE--*/
	"check voltage": "检查电压",
	/*--endif--*/
	/* msg at common.js(start) */
	" and ": " 到 ",
	" can't contain any special characters as below": "不能包含以下特殊字元",
	" characters": "字元",
	" contains invalid characters \;& and space!": "包含不正确的字元如\;& 和空白",
	" contains invalid characters!": "包含无效的字元!",
	" format error": "格式错误",
	" has illegal value or input format is incorrect !": "含有不合法数值或输入格式错误",
	" is invalid !": "是无效的",
	" is out of range !": "超出范围",
	" isn't a hex-digit number !": "不是十六进制数字",
	" isn't a number !": "不是数字",
	" must input !": "需要输入",
	" must input a value !": "需要输入数值",
	" requires 64 hex digits or ASCII code between 8 and 63.": "需要64个十六进制数字或是8到63个ASCII码",
	" value must NOT less than 0 !": "数值不能小于0 !",
	"(The hex digits are 0-9 and A-F)": "(十六进制数字包括0-9以及A-F)",
	"Clone MAC Address is disabled !": "複製 MAC 未启动",
	"Please input English word!": "请输入英文!",
	/* msg at common.js(end) */
	" (IP or Domain name)": " (IP 或 域名)",
	" (using/max)": " (使用/上限)",
	" already exists!": " 已经存在!",
	" contains invalid characters !": "包含无效的字元",
	" has been selected!": "已被选取!",
	" is already in the radio station list": "已经在电台列表中",
	" length is between ": "长度介于 ",
	" must be combination of alphanumeric characters and underscore!": "须为英文与数字以及底线符号的组合",
	"'s Rate": "的流量",
	"(Optional)": "(非必填)",
	"(bytes)": "(位元组)",
	"(minutes)": "(分钟)",
	"(seconds)": "(秒)",
	"128 Bit": "128位元",
	"3G Router": "3G Router",
	"64 Bit": "64位元",
	"802.11b": "802.11b",
	"802.11g": "802.11g",
	"802.11n": "802.11n",
	"802.1p Priority": "802.1p优先权",
	"802.1p": "802.1p",
	"802.1x Password": "802.1x密码",
	"802.1x User name": "802.1x使用者名称",
	"802.1x": "802.1x",
	"A static route is a pre-determined pathway that network information must travel to reach a specific host or network.": "由系统管理员因网路所需，设置固定的路径表，称为静态（static）路径表.",
	"ACS Configuration": "自动配置伺服器组态设定",
	"ACS URL is required!": "自动配置伺服器URL需填",
	"AP Isolation": "AP隔离",
	"AP List": "AP列表",
	"AP Only": "AP Only",
	"AP mode": "AP模式",
	"AP": "AP",
	"APR": "四月",
	"ARP Binding Settings": "ARP绑定设定",
	"ARP Binding Table": "ARP绑定表",
	"ARP spoofing correspondence": "ARP欺骗回复",
	"ARP spoofing prevention": "ARP欺骗攻击防御",
	"AUG": "八月",
	"Abnormal": "异常",
	"Access Control": "存取控制",
	"Access Point Name": "APN设定",
	"Account Name": "帐号名称",
	"Account": "帐户",
	"Action": "动作",
	"Active": "Active",
	"Add a DMZ Hos": "新增DMZ主机",
	"Add": "新增",
	"Address Mode": "位址模式",
	"Admin": "管理者",
	"Advanced Setting": "进阶设定",
	"Advanced Settings": "进阶设定",
	"Advertise Time": "通知间隔时间",
	"After restore data, device will reboot automatically! Are you sure to restore data?": "设定回復后, 装置将会自动重启! 确定要回復设定吗?",
	"Alias IP address should be in the same subnet with WAN IP address !": "Alias IP 位址应与WAN IP位址在同一网段",
	"Allow Internet access for the following MAC addresses": "允许网际网路根据MAC位址存取",
	"Allow Internet access for the following URL addresses": "允许网际网路根据URL位址存取",
	"Allow association access for the following MAC addresses": "允许以下MAC位址存取",
	"Already exists one port as WAN role for Normal NAT VLAN!": "Normal NAT VLAN下已经存在一个端口作为WAN的角色!",
	"Always": "永远",
	"Application": "应用程式",
	"Are you sure to delete these files?": "确定要删除这些文件吗? ",
	"At least a port between 1 and 4 must be selected!": "至少须要有个介于埠1到埠4的端口被选取!",
	"Audio Compressed Method": "音频压缩方式",
	"Audio Play List": "音乐列表",
	"Audio Stream Switch": "音频流开关",
	"Australia ISP service.": "澳洲网路服务.",
	"Authentication Length": "验证码长度",
	"Authentication Mode": "身份验证方式",
	"Authentication Server": "认证伺服器",
	"Auto Configuration(Stateless/DHCPv6)": "自动设置",
	"Auto Detect": "自动侦测",
	"Auto detect result :": "自动侦测结果 :",
	"Auto": "自动",
	"Auto-Configutation method": "自动设置方式",
	"BSSID": "BSSID",
	"BSSID1": "BSSID1",
	"BSSID2": "BSSID2",
	"Back": "返回",
	"Backup Settings": "备份设定",
	"Basic Rate": "基本速度",
	"Basic Settings": "基本设定",
	"Battle.Net multiplayers": "Battle.Net multiplayers",
	"Beacon Period": "Beacon间隔",
	"BigPond Account": "BigPond 使用者名称",
	"BigPond Mode": "BigPond 模式",
	"BigPond Password": "BigPond 使用者密码",
	"BigPond Server": "BigPond 伺服器",
	"BigPond": "BigPond",
	"Bind": "绑定",
	"Binding": "绑定",
	"Block Time": "封锁时间",
	"Block": "封锁",
	"Boot Code Version": "Boot Code 版本",
	"Bootcode": "引导装载程式",
	"Both": "两者",
	"Bridge Mode": "桥接器模式",
	"Bridge": "桥接器",
	"Broadcast Storm Control Function": "广播风暴控制功能",
	"Broadcast Storm Control": "广播风暴控制",
	"By IP": "基于IP",
	"By Port": "基于实体端口",
	"CPE Configuration": "用户端设备组态设定",
	"Cable Modem": "缆线数据机(Cable Modem)",
	"Cable/DSL": "Cable/DSL",
	"Cancel": "取消",
	"Change password ?": "确定修改密码吗 ?",
	"Changing was not done because designated IP address is same as present one": "变更尚未完成因为指定的IP位址没变",
	"Channel Width": "通道宽度",
	"Channel": "通道",
	"Choose File": "选择上传文件",
	"Choose": "选择",
	"Cipher Mode": "加密模式",
	"Clear": "清除",
	"Click Browse to select the firmware and then click OK to upgrade it.": "点选浏览并将路径指向您已下载的韧体,然后选择确定,即可开始更新韧体",
	"Client Filter": "使用者过滤",
	"Client Filtering": "使用者过滤",
	"Clone MAC": "修改WAN端MAC为:",
	"Comment": "附注",
	"Community Name": "社群名称(Community Name)",
	"Configuration file uploading...": "组态档上传中...",
	"Configuration rule can NOT be empty!": "组态规则内容不能为空!",
	"Configuration": "设定",
	"Configured": "已设定",
	"Congratulations! You have logout.": "恭喜! 您已经登出",
	"Connected Clients": "已连线用户",
	"Connected": "已连线",
	"Connecting": "连线中",
	"Connection ID": "连线 ID",
	"Connection Mode": "连线模式",
	"Connection Status": "连线状态",
	"Connection Time": "连线时间",
	"Connection Type": "连线方式",
	"Connection": "连线",
	"Current Firmware Version": "目前韧体版本",
	"Current Password": "目前的密码",
	"Current radio station": "目前播放的电台",
	"DDNS (Dynamic DNS) provides you on the Internet with a method to tie their domain name to a computer or server. DDNS allows your domain name to follow your IP address automatically by having your DNS records changed when your IP address changes.": "动态DNS是指不固定IP的主机，随IP的改变去设定网域名称与IP的对应关係.",
	"DDNS Ping Test": "DDNS连线测试",
	"DDNS Retry Time": "DDNS更新时间",
	"DDNS Server": "DDNS伺服器",
	"DDNS Status": "DDNS连线状态",
	"DDNS Update Interval": "DDNS 更新间隔",
	"DDNS": "DDNS",
	"DEC": "十二月",
	"DHCP Client List": "DHCP使用者列表",
	"DHCP Enabled": "启动DHCP",
	"DHCP Mode": "DHCP模式",
	"DHCP Server probe": "DHCP伺服器探测",
	"DHCP Server": "DHCP伺服器",
	"DHCP server will": "DHCP伺服器将会",
	"DLNA": "DLNA",
	"DMS Enable": "启动DLNA媒体伺服器",
	"DMZ Setting": "DMZ 设定",
	"DMZ host setting process: First, input the IP address of the computer worked as DMZ host in the LAN then select Add. Finally click OK to finish setting DMZ host.": "DMZ 主机设定过程: 输入在LAN端执行DMZ主机的IP位址,然后点选新增, 再点选确认后结束DMZ设定.",
	"DMZ": "DMZ",
	"DNS Proxy": "DNS代理伺服器",
	"DNS Server": "DNS伺服器",
	"DNS Settings": "DNS设定",
	"DNS information renewal finished successfully": "DNS资讯更新成功",
	"DNS": "DNS",
	"DSCP Base": "基于DSCP",
	"DSCP value collision": "DSCP 值冲突",
	"DSCP value": "DSCP 值",
	"DSCP": "DSCP",
	"Day": "天",
	"Default Gateway": "预设闸道器",
	"Default IP": "预设 IP",
	"Delete": "删除",
	"Deny Fragment Packets": "拒绝被切割 (fragment)的封包",
	"Deny Internet access for the following MAC addresses": "拒绝网际网路根据MAC位址存取",
	"Deny Internet access for the following URL addresses": "拒绝网际网路存取此URL位置",
	"Deny PING to the Gateway": "拒绝回应对闸道器Ping的封包",
	"Deny association access for the following MAC addresses": "禁止以下MAC位址存取",
	"Deny to Scan Security Port (113)": "拒绝扫描安全端口 (113)",
	"Description": "叙述",
	"Deselect All": "全取消",
	"Destination Network IP": "目的网路IP",
	"Detect": "侦测",
	"Detecting ...  Failed to show status": "侦测中 ...无法显示状态",
	"Detecting! Please wait....": "侦测中! 请稍后....",
	"Detection Port Scan Packets": "侦测扫描连接端口(Port)的封包",
	"Device will reboot automatically! All the settings will be restored to factory default value. If web page didn't refresh automatically, please check computer's internet settings and relogin again!": "装置将会自动重启! 所有的设定将会回復成出厂预设值. 若网页没有自动刷新, 请检查电脑的网路设定并重新登入!",
	"Device will reboot automatically! If web page didn't refresh automatically, please reload again!": "装置将会自动重启! 如果网页没有自动更新, 请重新载入!",
	"Device will reboot from Bridge mode to Router mode!": "从桥接器模式换成路由器模式装置将会重启!",
	"Dial Number": "拨号号码",
	"Dial-Up xDSL(PPPoE)": "PPPoE",
	"Disable ICMP Packets When Error is Encountered": "停用当错误发生,传送ICMP封包",
	"Disable MAC Address Control function": "关闭MAC位址控管功能",
	"Disable URL Filter function": "关闭URL过滤功能",
	"Disable VLAN function": "关闭VLAN功能",
	"Disable": "关闭",
	"Disabled": "关闭",
	"Discard NetBios Packets": "删除NetBios资料封包",
	"Discard PING from WAN side": "丢弃来自WAN端的Ping封包",
	"Disconnected": "断线",
	"Disconnecting": "断线中",
	"Displays WAN connection type and status.": "显示WAN连线方式与状态.",
	"Displays any illegal attempts to access your network.": "显示非经允许企图存取网路的记录.",
	"Displays system IP settings, as well as DHCP, NAT and Firewall status.": "显示系统IP设定, DHCP, NAT,和防火牆状态.",
	"Displays the number of connected clients, as well as the Router's firmware version numbers.": "显示连线的用户端数目和路由器的硬体与轫体版本.",
	"Do you really want to logout?": "您确定要登出吗?",
	"Do you really want to upgrade?": "确定真的要升级吗?",
	"Do you want to disable the SAMBA server?": "要关闭分享吗?",
	"Do you want to enable the SAMBA server shared with account(s)?": "要启动分享吗?",
	"Do you want to enable the SAMBA server shared without account(s)?": "要启动分享吗?",
	"Do you want to enable the printer server?": "要启动印表机伺服器吗?",
	"Does ISP provide more IP addresses?": "ISP提供其它更多IP位址?",
	"Domain Name Server": "网域名称伺服器",
	"Domain Name Servers are used to map an IP address to the equivalent domain name(e.g.www.china.com). Your ISP should provide the IP address for one or more domain name servers.": "网域名称伺服器会将IP位址对应到网域名称.您的网际网路服务者应提供一组或更多的网域名称伺服器的IP位址.",
	"Domain Name": "网域名称",
	"Download (max)": "下载 (最大)",
	"Download Bandwidth": "下载 频宽",
	"Download Max bandwidth should not be greater than Total download bandwidth": "下载最大频宽不应大于总下载频宽",
	"Download Max bandwidth": "下载最大频宽",
	"Download Min bandwidth should not be greater than Download Max bandwidth!": "下载最小频宽不应大于下载最大频宽!",
	"Download Min bandwidth should not be greater than Total download bandwidth": "下载最小频宽不应大于总下载频宽",
	"Download Min bandwidth": "下载最小频宽",
	"Download bandwidth should not lager than total download bandwidth": "下载频宽的和不应大于总下载频宽",
	"Download": "下载",
	"Duplicated IP address !": "重複的IP位址 !",
	"Duplicated MAC address. Replace with new IP address?": "重複的MAC位址.要取代原有的IP位址吗?",
	"Duplicated MAC address.": "重複的MAC位址.",
	"Duplicated VID value !": "重複的VID值 !",
	"Duplicated port range !": "重複的端口范围 !",
	"Duplicated": "重複的",
	"Duration": "维持时间",
	"Dynamic IP Address": "动态IP位址",
	"Dynamic IP": "动态IP位址",
	"Dynamic PPPoE": "动态PPPOE",
	"Dynamic Routing can be used to cache routes learned by routing protocols, thus allowing the automation of static routing maintenance. The router, using the RIP (Routing Information Protocol) protocol, determines the network packet's route based on the fewest number of hops between the source and the destination. ": "动态路由: 路由器根据路由协定提供的功能，自动学习和记忆网路运行情况，在需要时自动计算数据传输的最佳路径.",
	"Dynamic Routing": "动态路由",
	"ETH PORT": "Ethernet端口",
	"Edit playlist": "修改播放列表",
	"Eight hours": "八小时",
	"Email Log": "Email记录",
	"Enable Authentication": "启动认证",
	"Enable Auto-Configutation": "启动自动设置",
	"Enable DDNS": "启动 动态DNS",
	"Enable DHCP-PD": "启动DHCP-PD",
	"Enable Dynamic Routing": "启动 动态路由",
	"Enable Rule": "启动 规则",
	"Enable Static IP Mode": "启用固定IP模式",
	"Enable UPnP": "启动 UPnP",
	"Enable and shared with account(s)": "启动分享(需帐号)",
	"Enable and shared without account(s)": "启动分享(无需帐号)",
	"Enable": "启动",
	"Enabled VLAN function": "开启VLAN功能",
	"Enabled": "启用",
	"Encryption Mode": "加密模式",
	"English": "英文",
	"Enter the path and name of the upgrade file then click the OK button below.": "填入路径和更新韧体档案名称,然后点选下面的确定按钮",
	"Existing Client Filter": "使用者过滤",
	"Existing MAC Filter": "存在的MAC位址过滤",
	"Existing Static Routes": "存在的静态路由",
	"Existing": "存在的",
	"Extension": "扩充",
	"External Port": "外部端口",
	"FEB": "二月",
	"FPS": "画面更新率",
	"FRI": "星期五",
	"Failed to update": "更新失败",
	"Failed to upload files": "上传失败",
	"Failed! Please check the configuration file.": "升级失败! 请检查组态档案.",
	"Failed! Please check the firmware image and tool.": "升级失败! 请检查韧体档案及工具.",
	"File System in UTC Time": "档案系统使用世界标准时间",
	"File Explorer": "档案总管",
	"File Type": "档案类型",
	"File is being uploaded,please do not currently connected users to do anything on the management interface!": "文件正在上传,请当前连接的用户不要对管理界面做任何操作!",
	"File name is too long to be supported": "文件名太长,无法支持!",
	"File": "档名",
	"Filename": "档名",
	"Files Management": "文件管理",
	"Finish": "结束",
	"Firewall Options": "防火牆选项",
	"Firewall": "防火牆",
	"Firmware Date": "韧体日期",
	"Firmware Upgrade Status.": "韧体更新状态",
	"Firmware Upgrade": "轫体更新",
	"Firmware Version": "韧体版本",
	"Firmware": "韧体",
	"First Page": "第一页",
	"Fixed-IP xDSL": "固定IP位址(Fixed-IP)",
	"Flow Statistics": "流量统计",
	"Folder attribute reset to default": "档案属性回到预设值",
	"Forever": "永远",
	"Fragmentation Threshold": "分隔阀值",
	"From": "从",
	"Function Mode": "功能模式",
	"Function mode has been changed. Device will reboot...": "功能模式改变. 装置即将重启...",
	"Gateway Address": "闸道地址",
	"Gateway IP": "闸道器IP",
	"Gateway": "闸道器",
	"Get IPv6 DNS Server IP Address Automatically": "自动取得DNS位址",
	"Get current LAN IP automatically": "自动取得目前的LAN IP位址",
	"Green Field": "绿灯区模式",
	"Group Key Update Interval": "群组密钥更新间隔",
	"H323/Netmeeting passthrough": "H323/Netmeeting 穿透 (passthrough)",
	"HOST Settings": "HOST 设定",
	"HTTPS Port": "HTTPS端口",
	"Hacker Attack Patterns": "骇客攻击形态",
	"Half day": "半天",
	"Half hour": "半小时",
	"High Priority": "高优先",
	"High queue weight": "高伫列权重",
	"High": "高",
	"Higher weight should larger than lower weight": "高权重值应大于低权重值",
	"Host Name": "主机名称",
	"Host name can't empty!": "主机名称需输入!",
	"Hotspot Setting": "热点设定",
	"Hotspot": "热点",
	"ICMP Flood": "ICMP Flood",
	"ID": "ID",
	"IGMP Snooping": "IGMP 监听",
	"IP Address and Gateway Address are same !": "IP 位址和闸道器IP 一样",
	"IP Address of Virtual DMZ Host": "虚拟DMZ主机IP 位址",
	"IP Address": "IP 位址",
	"IP Base": "以IP为单位",
	"IP Pool Ending Address": "IP结束位址",
	"IP Pool Starting Address should not be greater than IP Pool Ending Address !": "IP起始位址不应大于IP结束位址 !",
	"IP Pool Starting Address": "IP起始位址",
	"IP Range": "IP 范围",
	"IP Spoofing": "IP Spoofing",
	"IP Unnumbered": "借用IP位址",
	"IP address : defined special IP for remote management , you should enter the IP here ( note : ISP provide more than 1 IP address , you should enable ( does ISP provide more IP address ?)  , and the IP address should match with remote management IP )": "IP 位址 : 为远端控制定义特殊的IP ,您必须在此输入IP (注释 : ISP 提供超过一个以上的IP位址时,您应该启用 (ISP提供其它更多IP位址 (详见WAN/连线)) ,以及输入之IP位址必须与远端管理的IP位址相同 ) )",
	"IP range collision!": "IP范围冲突",
	"IP": "IP",
	"IP/MAC Address of Virtual DMZ/SDMZ Host": "虚拟DMZ/SDMZ主机IP/MAC 位址",
	"IPv6 Address Range (End)": "IPv6地址结尾",
	"IPv6 Address Range (Start)": "IPv6地址起始",
	"IPv6 Connection Mode": "IPv6连线模式",
	"IPv6 DNS Settings": "IPv6 DNS设定",
	"IPv6 Default Gateway": "IPv6预设闸道",
	"IPv6 Live Time": "IPv6存活时间",
	"IPv6 Settings": "IPv6设定",
	"IPv6": "IPv6",
	"Idle Time Out": "閒置时间",
	"If you configure a virtual server, remote users accessing services such as Web or FTP on your LAN via public IP addresses can be automatically redirected to local servers configured with private IP address. In other words, depending on the requested service (TCP/UDP port number), the Router redirects the external service request to the appropriate server.": "如果您设定虚拟伺服器, 远端的使用者透过路由器的公用IP位址能自动地被导向已经设定好的私有IP位址, 以存取架设在这些私有IP位址的某些服务, 如WEB, FTP.",
	"Image": "图像",
	"In this page,you can change your administrator's password.": "在此,您可以更改您的管理者密码.",
	"Inbound": "流入",
	"Independent": "独立频宽",
	"Inform Interval": "通知间隔",
	"Inform": "通知",
	"Information": "资讯",
	"Interface": "介面",
	"Interfaces (Tag/Untag)": "介面 (Tag/Untag)",
	"Interfaces Settings": "介面设定",
	"Interfaces": "介面",
	"Internal Client": "内部用户",
	"Internal Port": "内部端口",
	"Internet": "网际网路",
	"Ipsec passthrough": "IPSec 穿透 (passthrough)",
	"Ipv6 Address": "WAN端IPv6位址",
	"Ipv6 Connection Mode": "IPv6连线模式",
	"JAN": "一月",
	"JUL": "七月",
	"JUN": "六月",
	"Key 1": "Key 1",
	"Key 2": "Key 2",
	"Key 3": "Key 3",
	"Key 4": "Key 4",
	"Key Selection": "秘钥选择",
	"Key": "秘钥",
	"L2TP Account": "L2TP 使用者名称",
	"L2TP Mode": "L2TP 模式",
	"L2TP Password": "L2TP 使用者密码",
	"L2TP Server": "L2TP 伺服器",
	"L2TP Settings": "L2TP 设定",
	"L2TP can support multi-protocol Virtual Private Networks (VPN).": "L2TP 可支援多种通讯协定的虚拟私人网路(VPN).",
	"L2TP passthrough": "L2TP 穿透 (passthrough)",
	"L2TP": "L2TP",
	"LAN / DHCP Client List": "LAN / DHCP 使用者列表",
	"LAN / Settings": "LAN / 设定",
	"LAN IP address can't be the same with WAN IP address !": "LAN IP 位址不能与WAN IP位址一样",
	"LAN IPv6 Address": "LAN端IPv6位址",
	"LAN Ipv6 Address": "LAN端IPv6位址",
	"LAN Ipv6 Connection - Local Address": "LAN端IPv6子网路",
	"LAN MAC Address": "LAN MAC位址",
	"LAN Settings": "LAN 设置",
	"LAN": "LAN",
	"LAN-1": "LAN-1",
	"LAN-2": "LAN-2",
	"LAN-3": "LAN-3",
	"LAN-4": "LAN-4",
	"Land Attack": "Land Attack",
	"Language": "语言",
	"Last Page": "最后一页",
	"Layer 2 Tunneling Protocol can support multi-protocol Virtual Private Networks (VPN).": "L2TP可支援多种通讯协定的虚拟私人网路(VPN).",
	"Lease Time": "租约时间",
	"List the system activities .": "列出系统记录.,",
	"Listen Mode": "被动模式",
	"Local Area Network (LAN) Address Auto-Configuration Settings": "LAN位址自动设置",
	"Local Area Network (LAN) IPv6 Address Settings": "IPv6的LAN设定",
	"Log Server": "记录伺服器",
	"Log Settings": "记录设定",
	"Log": "记录",
	"Login Account": "密码设定",
	"Login": "登入",
	"Logout": "登出",
	"Long": "长",
	"Low Priority": "低优先",
	"Low queue weight": "低伫列权重",
	"Low": "低",
	"MAC Address Clone": "複製MAC位址",
	"MAC Address Control": "MAC位址控管",
	"MAC Address of Virtual SDMZ Host": "虚拟SDMZ主机MAC位址",
	"MAC Address": "MAC 位址",
	"MAC Cloning": "启动MAC位址複製功能",
	"MAC Filtering": "MAC过滤",
	"MAC address of WAN. If you use Cable Modem you must input it. You can use the Clone MAC Address button to copy the MAC address of the Ethernet Card installed by your ISP and replace the WAN MAC address with this MAC address.": "WAN的MAC位址. 如果您使用缆线数据机 (Cable Modem),您必须输入MAC位址.您可使用複製MAC位址按钮去複製您网际网路服务者帮您安装的乙太网路卡的MAC位址,以取代WAN MAC位址.",
	"MAR": "三月",
	"MAY": "五月",
	"MBSSID Isolation": "MBSSID隔离",
	"MON": "星期一",
	"MSN passthrough": "MSN 穿透 (passthrough)",
	"MTU value is changed! Device will reboot!": "MTU值变更! 装置将会重启!",
	"MTU": "最大传输单位",
	"Manage Radio Station": "管理网路电台",
	"Management VID": "管理者VID",
	"Management": "管理",
	"Manegement VID not match anyone of group VID! It cause web page can't be opened!": "管理者VID与任一群组VID不一致! 网页将无法开启.",
	"Manual Select": "手动选择",
	"Manual Setting": "手动设定",
	"Mapping Ports": "对应端口",
	"Max bandwidth": "最大频宽",
	"Maximum Idle Time": "最大閒置时间",
	"Maximum Limit": "最大限制",
	"Medium Priority": "中优先",
	"Medium queue weight": "中伫列权重",
	"Medium": "中",
	"Members": "成员",
	"Metric": "成本(Metric)",
	"Min bandwidth": "最小频宽",
	"Minimum Guarentee": "最小保障",
	"Minutes": "分钟",
	"Misc": "其它",
	"Mixed 802.11b, 802.11g": "溷合802.11b, 802.11g",
	"Mixed 802.11b, 802.11g, 802.11n": "溷合802.11b, 802.11g, 802.11n",
	"Mode": "模式",
	"Modify": "修改",
	"More IP addresses": "其它更多IP位址",
	"Multicast Storm Control": "多播风暴控制",
	"Multicast to Unicast": "多点传送转单点传送",
	"NAT": "NAT",
	"NOT support multiple Wan.": "不支援多个Wan端口.",
	"NOV": "十一月",
	"NTP Server": "NTP 伺服器",
	"Name": "名称",
	"Network Mode": "网路模式",
	"New Password": "新密码",
	"New input password is not consistent!": "输入的新密码不一致",
	"Next Page": "下一页",
	"Next station": "下一电台",
	"Next": "下一步",
	"No WAN port setting.": "WAN端口没有设定",
	"No file chosen": "没有选择文件",
	"No timeout": "不设定閒置时间",
	"No": "No",
	"No.": "项次",
	"Non-Standard FTP Port": "非标准 FTP Port",
	"Normal NAT VLAN": "Normal NAT VLAN",
	"OCT": "十月",
	"OFF": "关",
	"ON": "开",
	"Obtain an IP address automatically from your service provider.": "自动获得您的网际网路服务者提供的IP位址.",
	"Occurred system error": "发生系统错误",
	"One day": "一天",
	"One hour": "一小时",
	"One week": "一星期",
	"Open System": "开放系统",
	"Operating Mode": "操作模式",
	"Options": "选项",
	"Original password is not correct!": "目前的密码输入错误",
	"Outbound": "流出",
	"Overwrite this file, are you sure?": "当前文件夹下已有相同的此文件,确定要复盖吗？",
	"PBC": "按钮设定",
	"PIN Code": "个人识别码",
	"PPP Tunneling Protocol can support multi-protocol Virtual Private Networks (VPN).": "PPTP可支援多种通讯协定的虚拟私人网路(VPN).",
	"PPP over Ethernet is a common connection method used for xDSL.": "PPPoE是一种普遍的使用xDSL的连线方式.",
	"PPPOE Account": "PPPOE 使用者名称",
	"PPPOE Mode": "PPPOE 模式",
	"PPPOE Password": "PPPOE 使用者密码",
	"PPPOE": "PPPOE",
	"PPPoE connection mode": "PPPoE连线模式",
	"PPPoE": "PPPoE",
	"PPTP Account": "PPTP 使用者名称",
	"PPTP Mode": "PPTP 模式",
	"PPTP Password": "PPTP 使用者密码",
	"PPTP Server": "PPTP 伺服器",
	"PPTP Settings": "PPTP设定",
	"PPTP passthrough": "PPTP 穿透 (passthrough)",
	"PPTP": "PPTP",
	"PVID": "PVID",
	"Packets/10ms": "封包/10ms",
	"Parent directory": "返回上一级",
	"Passthrough": "穿透",
	"Password": "密码",
	"Period": "週期",
	"Personal Identification Number": "PIN码设定",
	"Ping Threshold": "阀值",
	"Ping of Death": "Ping of Death",
	"Please enter the record file name:": "请输入录音档名:",
	"Please insert a SD card before starting video recording": "开始录像前,请插入SD卡",
	"Please retype your password": "请重複确认密码",
	"Please save settings first!": "请先储存设定!",
	"Please select a radio station and modify it": "请选择电台并且编辑",
	"Please select file to restore settings!": "请选择档案做设定回復!",
	"Please select file to upgrade system!": "请选择档案做系统升级!",
	"Please select option!": "请选择项目!",
	"Please select the days of the week!": "请选择星期几!",
	"Please select the file to be deleted!": "请选择需要删除的文件!",
	"Please select the file to be uploaded!": "请选择需要上传的文件!",
	"Please wait ...": "请稍后 ...",
	"Port : the remote management port !": "端口 : 远端管理使用的连接端口(Port).",
	"Port Base": "以Port为单位",
	"Port INTERNET already exists!": "INTERNET埠已经存在!",
	"Port INTERNET must NOT be selected!": "INTERNET埠必须不能被选取!",
	"Port INTERNET must be selected!": "INTERNET埠必须被选取!",
	"Port INTERNET": "网际网路端口",
	"Port Mapping List": "端口映射表",
	"Port Mapping": "端口映射",
	"Port Triggering": "端口触发",
	"Port WIFI": "无线端口",
	"Port range collision!": "端口范围冲突",
	"Port rate Control": "埠流量控制",
	"Port": "端口",
	"Port-": "埠-",
	"Port-1": "埠-1",
	"Port-2": "埠-2",
	"Port-3": "埠-3",
	"Port-4": "埠-4",
	"Port-5": "埠-5",
	"Pre-shared Key": "预共享密钥模式",
	"Prev Page": "前一页",
	"Prevent Network Attack</b><br>It can protect your network to prevent hackers attack.": "避免网路攻击,提供保护,以避免骇客攻击网路.",
	"Previous station": "前一电台",
	"Primary DNS Server": "主要DNS",
	"Primary DNS": "惯用的DNS伺服器",
	"Primary Domain Name Server (DNS)": "主要DNS",
	"Printer Server List": "印表机伺服器列表",
	"Printer server": "印表机伺服器",
	"Printer": "印表机",
	"Priority": "优先权",
	"Private IP": "私有IP位址",
	"Private Port": "私有服务端口",
	"Profile": "Profile",
	"Protocol": "通讯协定",
	"Public IP Address": "公用IP位址",
	"Public Port": "公用服务端口",
	"Queue map": "伫列优先权",
	"Quick Setup": "快速设置",
	"R": "读",
	"R/W": "读/写",
	"Radio Preamble": "前置位元",
	"Radio Station Lists": "电台列表",
	"Radius Verified": "Radius已验证",
	"Radius account Port": "Radius帐户端口",
	"Radius auth port": "Radius认证端口",
	"Radius server IP Address/Domain Name": "Radius伺服器位址",
	"Radius server Port": "Radius伺服器端口",
	"Radius server Shared Secret": "Radius伺服器共享密钥",
	"Rate Control": "流量控制",
	"Rate control by DSCP value": "流量控制基于DSCP权重",
	"Rate control by HFSC": "流量控制基于HFSC",
	"Rate control by IP": "流量控制基于IP",
	"Rate control by Physical port": "流量控制基于实体端口",
	"Rate": "速率",
	"Re-Type Password": "再次输入密码",
	"Re-type Password": "再次确认新密码",
	"Ready": "准备",
	"Reboot Immediately": "立即重启",
	"Reboot": "重启",
	"Recipient Email Address": "收件者的电子邮件信箱",
	"Record completed": "录音完毕",
	"Record": "记录",
	"Recording": "录音中",
	"Refresh Port Mapping": "更新端口映射",
	"Refresh": "更新",
	"Release": "释放",
	"Reload": "页面重载",
	"Remaining Time": "剩馀时间",
	"Remote Host": "远端主机",
	"Remote Log": "远端记录设定",
	"Remote Management": "远端管理",
	"Remove": "移除",
	"Renew": "更新",
	"Repeater Mode": "Repeater模式",
	"Repeater": "Repeater",
	"Request IP address": "要求IP位址",
	"Reset": "重置",
	"Resolution": "解析度",
	"Restart Device": "重启",
	"Restart System": "重新启动",
	"Restore Factory Default": "回復出厂设定",
	"Restore Settings": "回復设定",
	"Retype password": "确认密码",
	"Role": "角色",
	"Root directory": "返回根目录",
	"Router Live Time": "Router存活时间",
	"Router WPS PIN Code": "Router的个人识别码",
	"Router": "路由器",
	"Routing Table List": "路由表",
	"Routing Table": "路由表",
	"Routing": "路由",
	"Rule Enabled": "启动规则",
	"Rule": "规则",
	"Rules Listing": "规则清单",
	"Russia PPP Tunneling Protocol(Dual Access) can support multi-protocol Virtual Private Networks (VPN).": "Russia PPTP(Dual Access)可支援多种通讯协定的虚拟私人网路(VPN).",
	"Russia PPP over Ethernet(Dual Access) is a common connection method used for xDSL.": "Russia PPPoE(Dual Access)是一种普遍的使用xDSL的连线方式.",
	"Russia PPPOE(Dual Access)": "Russia PPPOE(Dual Access)",
	"Russia PPTP(Dual Access)": "Russia PPTP(Dual Access)",
	"SAMBA server": "SAMBA伺服器",
	"SAT": "星期六",
	"SDMZ": "SDMZ",
	"SEP": "九月",
	"SMS4": "SMS4",
	"SMTP Server IP address": "SMTP伺服器的IP位址",
	"SMTP Server": "SMTP 伺服器",
	"SNMP Settings": "SNMP设定",
	"SNMP": "SNMP",
	"SSID": "SSID",
	"SSID1": "SSID1",
	"SSID2": "SSID2",
	"STA": "STA",
	"SUN": "星期天",
	"Samba": "Samba",
	"Sample Rate": "取样率",
	"Save": "储存",
	"Scanning": "扫描",
	"Secondary DNS Server": "次要DNS",
	"Secondary DNS": "其他DNS伺服器",
	"Secondary Domain Name Server (DNS)": "次要DNS",
	"Security Log": "安全记录",
	"Security Mode": "安全模式",
	"Security": "安全",
	"Select All": "全选",
	"Select files to upload": "选择上传文件",
	"Select/Deselect All": "全选/取消",
	"Selection": "选择",
	"Send Email to": "传送Email至",
	"Send Email! Please wait....": "Email传送中! 请稍后....",
	"Send Email": "传送电子邮件",
	"Send log IP address": "传送记录的IP位址",
	"Send log to": "传送记录至",
	"Send": "传送",
	"Sender Email Address": "寄件者的电子邮件信箱",
	"Sender": "寄件者",
	"Server IP": "伺服器IP",
	"Server": "伺服器",
	"Service IP Address": "服务IP位址",
	"Service Name": "服务名称",
	"Set As PVID": "当作PVID",
	"Set": "设置",
	"Settings": "设定",
	"Share": "共享频宽",
	"Shared System": "共享金钥",
	"Short Guard Interval": "缩短保护间隔",
	"Short Packet": "Short Packet",
	"Short": "短",
	"Signal": "讯号",
	"Signal(%)": "讯号(%)",
	"Simplified Chinese": "简体中文",
	"Size (bytes)": "大小 (位元组)",
	"Size": "大小",
	"Smurf Attack": "Smurf Attack",
	"Snork Attack": "Snork Attack",
	"Some applications require an application level gateway throught the router.": "某些应用程式需开启应用层闸道器 (Application Level Gateway)来通过此台路由器.",
	"Some applications require multiple connections, such as Internet gaming, video conferencing, Internet telephony and others. These applications cannot work when Network Address Translation (NAT) is enabled. If you need to run applications that require multiple connections,-specify the port normally associated with an application in the Trigger Port field,select the protocol type as TCP or UDP, then enter the public ports associated with the trigger port to open them for inbound traffic.": "某些应用程式需要多重连接,例如网路游戏, 视讯会议,网路电话. 这些应用程式在启用NAT模式下无法使用.",
	"Song Name": "歌曲名称",
	"Special Application": "特殊应用程式",
	"Specify the WAN connection type required by your Internet Service Provider. Please select your WAN connection from the following:": "请从以下选择您网际网路服务者提供的WAN连线方式:",
	"Start to firmware upgrade!": "开始进行韧体更新",
	"Starting Port should not be greater than Ending Port!": "起始端口不应大于结束端口 !",
	"Starting Public Port should not be greater than Ending Public Port!": "起始公用服务端口不应大于结束公用服务端口 !",
	"Starting Time should be less than Ending Time!": "起始时间应小于结束时间 !",
	"Starting Trigger Port should not be greater than Ending Trigger Port!": "起始触发端口不应大于结束触发端口 !",
	"Stateful (DHCPv6)": "无状态",
	"Stateless": "全状态",
	"Static Client Configuration": "静态使用者设定",
	"Static DNS Server": "固定DNS伺服器",
	"Static IP Address": "静态IP位址",
	"Static IP": "静态IP位址",
	"Static IPv6": "静态IPv6",
	"Static PPPoE": "静态PPPOE",
	"Static Routes Configuration": "静态路由设定",
	"Static Routing": "静态路由",
	"Static": "静态",
	"Station List": "Station列表",
	"Station Name": "电台名称",
	"Station name can not be empty or only contains whitespaces": "电台名称不能为空或是只有空白字元",
	"Station name can not be empty": "电台名称不能为空",
	"Status": "状态",
	"Stop play": "停止播放",
	"Stop": "停止",
	"Storage": "存储",
	"Stream": "串流",
	"Su,Mo,Tu,We,Th,Fr,Sa": "日,一,二,三,四,五,六",
	"Subnet Mask": "子网路遮罩",
	"Subnet Prefix Length": "子网路prefix长度",
	"Subnet mask": "子网路遮罩",
	"Subscribe Timeout": "Subscribe Timeout",
	"Successfully updated": "更新成功",
	"Supply Mode": "主动模式",
	"Switching to STA mode might make you unable to connect to DUT if authentication information is wrong": "如果认证错误,切换到Station Mode后可能导致无法和DUT连线",
	"Syn Flood": "Syn Flood",
	"Syn Threshold": "阀值",
	"Sync with host": "与本机同步",
	"System Date": "日期 / 时间",
	"System Log": "系统记录",
	"System Settings": "系统",
	"System Time": "系统时间",
	"System Up Time": "系统启动时间",
	"System configuration is reset to the factory default settings. Default settings are:": "系统回復至出厂设定: 原始设定为 :",
	"System rebooted, linking.......": "系统已重启，装置连结中 ",
	"System": "系统",
	"Sytem Status": "连线状态",
	"TCP Null Scan": "TCP Null Scan",
	"TCP Syn Flood": "TCP Syn Flood",
	"TCP": "TCP",
	"TCP/IP protocol setting include IP address, subnet mask ,gateway and DNS server. It is not very easy to Config TCP/IP protocol correctly for all computers in your Lan. Fortunately, the DHCP server provide this fuction.If you employ this DHCP server function you can let it Config TCP/IP protocol automatically.": "TCP/IP通讯协定设定包含IP位址,子网路遮罩,闸道器,和DNS伺服器. 将区域网路裡所有电脑正确地设定TCP/IP通讯协定并不容易. DHCP伺服器能提供自动设定的功能.",
	"TFTP Client": "TFTP客户端",
	"THU": "星期四",
	"TUE": "星期二",
	"Tag / Untag": "标记/未标记",
	"Tag": "标籤",
	"Target AP": "目标AP",
	"Testing ...  ": "侦测中 ...",
	"Testing ...  Failed to update": "侦测中 ...更新失败",
	"The DHCP client list allows you to see which clients are connected to the Router via IP address, host name, and MAC address.You can select static to fixed it.": "DHCP使用者列表允许您透过主机名称,MAC位址检视哪些用户连接上这台路由器. 您可选择静态或动态.",
	"The Gateway acts as DHCP Server": "闸道器设为DHCP伺服器",
	"The VID ": "此VID ",
	"The ending day is error!": "结束日期错误!",
	"The maximun rule is ": "最大规则数目是 ",
	"The number of radio station has reached the maximum": "可加入的广播电台数目已达上限",
	"The radio station name contains any of these illegal characters": "电台名称含有任何这些非法字元",
	"The router IP address to LAN. The factory fault setting is 192.168.1.1.You can change it according to your requirements.": "这部路由器LAN端的IP位址,原始预设值为: 192.168.1.1. 您可根据您的需求做变更.",
	"The routing table display the current routing information in system.": "路由表显示目前此系统的路由讯息.",
	"The starting day is error!": "起始日期错误!",
	"The starting day should be smaller than the ending day!": "起始日期应小于或等于结束结束日期!",
	"The starting month should be smaller or equal to the ending month!": "起始月份应小于或等于结束月份!",
	"There already exists a remote management rule!": "已经存在一个远端管理规则!",
	"There is a duplicated port between Port 1 and Port 4 in this profile!": "此profile有重复的端口介于埠1和埠4!",
	"There is a duplicated port between Port 1 and Port 4, and WIFI port in this profile!": "此profile有重复的端口介于埠1和埠4,及WIFI埠!",
	"There is a duplicated port between Port 1 and Port 5 in this profile!": "此profile有重复的端口介于埠1和埠5!",
	"There is a duplicated port between Port 1 and Port 5, and WIFI port in this profile!": "此profile有重复的端口介于埠1和埠5,及WIFI埠!",
	"There is no port selected!": "没有端口被选取!",
	"There's already exist one entry which has the same Network IP.\n Replace with it?": "已经存在一个entry有着相同的网路IP位址.\n要取代它吗?",
	"This functionality allows one or more public port to be mapping by multiple internal users. Enter the internal IP address you wish to map into the Global port field. Enter global port that will mapping the internal IP.": "这个功能允许多个使用者共享一个或多个公用IP位址. 输入您想要分享的IP位址.",
	"Threshold": "阀值",
	"Time Zone": "时区",
	"Time": "时间",
	"To configure the URL Filtering feature, use the table as above to specify the web sites (www.somesite.com) and/or web URLs containing the keyword you want to filter on your network.": "当您使用URL过滤功能时,于左方表格明确填入Web网址(例如: www.somesite.com), 或者输入您想要过滤的关键字.",
	"Too many entries, maximum is ": "超出可设定项目数, 最多为",
	"Tools": "工具",
	"Total download bandwidth": "总下载频宽",
	"Total upload bandwidth": "总上传频宽",
	"Traditional Chinese": "繁体中文",
	"Transmission Power": "传输功率",
	"Transmission Rate": "传输率",
	"Trap IP": "Trap的IP位址",
	"Trap Name": "Trap的名称",
	"Trap Settings": "Trap相关设定",
	"Trigger Port": "触发端口",
	"Trigger Type overlapped !": "触发类型重叠",
	"Trigger Type": "触发类型",
	"Triple Play VLAN": "Triple Play VLAN",
	"Two days": "二天",
	"Two hours": "二小时",
	"Two weeks": "二星期",
	"Type your IP netmask, gateway etc.": "请输入您的IP,子网路遮罩及闸道器位置等.",
	"Type": "类型",
	"UAPSD": "UAPSD",
	"UDP Port Loop": "UDP Port Loop",
	"UDP": "UDP",
	"UPnP (Universal Plug and Play) allows automatic discovery and configuration of equipment attached to your LAN. UPnP is supported by Windows ME, XP, or later. It provides compatibility with networking equipment, software and peripherals of the over 400 vendors that cooperate in the Plug and Play forum. ": "UPnP(通用随插即用 )，能让各种不同的连线装置，不需经过设定，省去複杂的安装程序，就能连上网路.",
	"UPnP Port Number": "UPnP 端口",
	"UPnP": "UPnP",
	"URL Filter Control": "URL过滤功能",
	"URL Filtering": "URL过滤",
	"URL can not be empty or only contains whitespaces": "URL不能为空或是只有空白字元",
	"URL can not be empty": "URL不能为空",
	"URL filter string": "URL过滤条件",
	"USB": "USB",
	"UUID": "通用唯一识别码",
	"Unable to show status. Please try again!": "无法显示状态. 请重试!",
	"Upgraded successfully!": "升级成功!!",
	"Upgrading! Please wait....": "升级中!请等待..",
	"Upload Bandwidth": "上传 频宽",
	"Upload Max bandwidth should not be greater than Total upload bandwidth": "上传最大频宽不应大于总上传频宽",
	"Upload Max bandwidth": "上传最大频宽",
	"Upload Min bandwidth should not be greater than Total upload bandwidth": "上传最小频宽不应大于总上传频宽",
	"Upload Min bandwidth should not be greater than Upload Max bandwidth!": "上传最小频宽不应大于上传最大频宽!",
	"Upload Min bandwidth": "上传最小频宽",
	"Upload bandwidth should not lager than total upload bandwidth": "上传频宽和不应大于总上传频宽",
	"Upload files successfully!": "文件上传成功",
	"Upload": "上传",
	"Uploading files. Current connected users please do not touch the management interface!": "档案上传中,请耐心等待",
	"Use a static IP address. Your service provider gives a static IP address to access Internet services.": "使用静态IP位址. 您的网际网路服务者提供您一个静态IP位址可存取网路服务.",
	"Use the following IPv6 DNS Server IP Address": "使用以下IP位址",
	"User Name": "使用者名称",
	"VLAN setting will disable.": "虚拟区网设定将会关闭.",
	"Video Compressed Method": "影像压缩方式",
	"Virtual DMZ Hosts": "虚拟DMZ主机",
	"Virtual Host Option": "虚拟主机选项",
	"Virtual SDMZ Hosts": "虚拟SDMZ主机",
	"Virtual Server": "虚拟伺服器",
	"Volume control": "音量控制",
	"W": "写",
	"WAN Connection Mode": "WAN连线模式",
	"WAN IP address can't be the same with LAN IP address !": "WAN IP 位址不能与LAN IP位址一样",
	"WAN IP": "WAN IP",
	"WAN IPv6 Address": "WAN端IPv6位址",
	"WAN Interface IP": "WAN介面IP位址",
	"WAN Interface Settings": "WAN介面设定",
	"WAN MAC Address": "WAN MAC 位址",
	"WAN Mode": "WAN 模式",
	"WAN Physical Gateway": "WAN 实体闸道器",
	"WAN Physical IP Address": "WAN 实体IP位址",
	"WAN Physical Primary DNS": "WAN 实体惯用DNS伺服器",
	"WAN Physical Secondary DNS": "WAN实体其他DNS伺服器",
	"WAN Physical Setting": "WAN实体设定",
	"WAN Physical Subnet Mask": "WAN 实体子网路遮罩",
	"WAN Static IP": "WAN 固定IP",
	"WAN is connected to the Internet using a USB-based 3G/UMTS/HSDPA dongle.": "使用PPP透过USB 3G dongle存取网际网路.",
	"WAN port PVID duplicated with LAN port.": "WAN端口PVID与LAN端口重复.",
	"WAN": "WAN",
	"WDS Mode": "WDS模式",
	"WDS": "WDS",
	"WED": "星期三",
	"WEP Key Selection": "WEP钥选择",
	"WEP Key1": "WEP Key1",
	"WEP Key2": "WEP Key2",
	"WEP Key3": "WEP Key3",
	"WEP Key4": "WEP Key4",
	"WISP mode": "WISP模式",
	"WISP": "WISP",
	"WMM": "WMM",
	"WPS": "WPS",
	"Wide Area Network (WAN) IPv6 address settings": "IPv6的WAN设定",
	"Windows messenger(file transfer)": "Windows messenger(档案传输)",
	"Wireless BSSID": "无线BSSID",
	"Wireless Channel": "通道编号",
	"Wireless Network Mode": "无线网路模式",
	"Wireless Router": "Wireless Router",
	"Wireless SSID broadcast": "无线SSID广播",
	"Wireless SSID": "无线SSID",
	"Wireless Setting": "无线设置",
	"Wireless is not enabled.": "无线功能尚未启动",
	"Wireless": "Wireless",
	"Wizard": "连线精灵",
	"Working Mode": "执行模式",
	"Wrong User-ID or Password or overdue user": "错误的使用者ID或密码或逾期使用者",
	"Yes": "启动",
	"You can block certain client PCs accessing the Internet based on MAC address.": "特定的使用者电脑,根据MAC位址限制他们存取网际网路.",
	"You can filter Internet access for local clients based on IP addresses, application types, (i.e., HTTP port), and time of day.": "您可以设定某些规则允许或限制您的LAN 用户端存取网际网路,例如以IP位址,某些应用类别 (如: HTTP port), 或时间限制.",
	"You can not make all port in a rule of Bridge role.": "不能将所有的埠都选为某个规则内的桥接角色.",
	"You can select only one port as WAN role for Normal NAT VLAN!": "Normal NAT VLAN下只能选取一个端口作为WAN的角色!",
	"You can select your timezone,then server can sync time from internet ntp server.": "您可以选择一个您的时区,然后本机将会与网际网路上的NTP伺服器同步.",
	"You can use the Status screen to see the connection status of WAN/LAN interfaces, firmware version numbers, and the number of connected clients to your network. The following items are included in this screen:": "您可以使用状态介面去检查WAN和LAN的连线状态, 韧体版本, 和连线的用户端数目.",
	"You have not logout yet.": "您尚未登出",
	"alert filename invalid": "文件名不能包含下列字符之一[/ , \\ , : , * , ? , \" , < , > , | , $ ]",
	"alert filename long": "文件名太长,无法支持",
	"alert same filename": "当前文件夹下已有相同的此文件,确定复盖吗?",
	"and second channel is above": "且第二通道在上",
	"and second channel is below": "且第二通道在下",
	"auto-connect": "自动连线",
	"bytes": "位元组",
	"check if camera exists": "检查摄像头是否存在",
	"check if storage exists": "检查存储装置是否存在",
	"configure ": "组态 ",
	"confirm delete": "确定要删除这个文件吗?",
	"default Bridge": "预设桥接器",
	"default Router": "预设路由器",
	"download (max)": "下载(最大)",
	"files button": "选择上传文件",
	"files delete": "删除",
	"files disk icon": "磁盘图标",
	"files disk name": "磁盘名称",
	"files name": "文件名称",
	"files select": "全选/取消",
	"files selection": "文件选择",
	"files size": "文件大小",
	"files text": "没有选择文件",
	"files type": "文件类型",
	"files upload failed": "上传失败!",
	"files upload success": "文件上传成功!",
	"files upload warn": "文件正在上传,请当前连接的用户不要对管理界面做任何操作!",
	"files uploaded": "请选择需要上传的文件!",
	"keep-alive": "持续连线",
	"manual-on": "手动连线",
	"media share": "视频共享",
	"music share": "音乐共享",
	"packets per second": "packets per second",
	"pic share": "图片浏览",
	"seconds (0: No timeout)": "秒 (0: 无逾期时间)",
	"seconds": "秒",
	"size unit": "",
	"to": "至",
	"unit:Bytes": "单位:Bytes",
	"upload (max)": "上传 (最大)",
	'ZZZ': 'ZZZ'
};
