#ifndef SPOTIFY_MSG_HANDLER_H
#define SPOTIFY_MSG_HANDLER_H

enum {
    NOTIFY_SET_DISPLAY_NAME,
    NOTIFY_SPOTIFY_STOP,
    NOTIFY_SPOTIFY_TOGGLE,
	NOTIFY_SPOTIFY_VOLUME,
    MAX_NOTIFY_SIZE,
};

void ipc_init();

#endif

