#define BASIC_SDK                                1
#define CCONFIG_REQUEST_QUEUE_LIMIT              3
#define CONFIG_HEARTBEAT_INTERVAL                12
#define CONFIG_MAX_MESSAGE_LENGTH                2048
#define CONFIG_REQTIMEOUT_INTERVAL               6
#define CONFIG_SDS                               1
#define DEBUG                                    1
#define HAVE_DLFCN_H                             1
#define HAVE_INTTYPES_H                          1
#define HAVE_MEMORY_H                            1
#define HAVE_PTHREAD                             1
#define HAVE_PTHREAD_PRIO_INHERIT                1
#define HAVE_STDINT_H                            1
#define HAVE_STDLIB_H                            1
#define HAVE_STRING_H                            1
#define HAVE_STRINGS_H                           1
#define HAVE_SYS_STAT_H                          1
#define HAVE_SYS_TYPES_H                         1
#define HAVE_UNISTD_H                            1
#define LT_OBJDIR                                ".libs/"
#define PACKAGE                                  "alink-agent"
#define PACKAGE_BUGREPORT                        ""
#define PACKAGE_NAME                             "alink-agent"
#define PACKAGE_STRING                           "alink-agent 0.1"
#define PACKAGE_TARNAME                          "alink-agent"
#define PACKAGE_URL                              ""
#define PACKAGE_VERSION                          "0.1"
#define STDC_HEADERS                             1
#define VERSION                                  "0.1"
