# 
# OpenWrt
#
# This is free software, licensed under the GNU General Public License v2.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=MPlayer
PKG_VERSION:=1.3.0
PKG_RELEASE:=1

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
#PKG_SOURCE_URL:=http://www.mplayerhq.hu/MPlayer/releases/
DL_DIR=$(CURDIR)

include $(INCLUDE_DIR)/package.mk
#include $(INCLUDE_DIR)/nls.mk

PKG_BUILD_PARALLEL:=1

define Package/mplayer
  SECTION:=multimedia
  CATEGORY:=Multimedia
  TITLE:=MPlayer, the movie player
  URL:=http://www.mplayerhq.hu
  #DEPENDS:=+libjpeg +libpng +zlib +libfreetype +fontconfig $(ICONV_DEPENDS) +libmad +libaa +giflib +fribidi +libtheora +libggi
  #DEPENDS+=+alsa-lib +libfaad2 +libmpcdec +libmpg123 +libspeex +libpthread
  DEPENDS:=+alsa-lib +libpthread +librt +zlib
endef

define Package/mplayer/description
  MPlayer is a movie player which runs on many systems.
endef

#TARGET_CFLAGS += -std=c99 -DPATH_MAX=512 -D_GNU_SOURCE


#		--extra-cflags="$(TARGET_CFLAGS)" \
#		--extra-ldflags="$(TARGET_LDFLAGS)" \
#--extra-ldflags="-L/workplace3/panther.cchip/openwrt/staging_dir/target-mipsel-openwrt-linux/usr/lib" \
#--extra-cflags="-I/workplace3/panther.cchip/openwrt/staging_dir/target-mips-openwrt-linux/usr/include"


# mplayer makefile is soooo broken.  have to specify libs by hand, if
# compileing with --enable-system-ffmpeg
# TARGET_CFLAGS+= -std=c99 -DPATH_MAX=512 -D_GNU_SOURCE
# -lavcore

# todo: remove once building correctly
#MAKE_FLAGS = -j4
define Build/Configure
	(cd $(PKG_BUILD_DIR); \
		./configure \
		--enable-cross-compile \
		--enable-big-endian \
		--prefix=/usr \
		--confdir=/etc \
		--target=$(TARGET_CROSS) \
		--host-cc=gcc \
		--cc="$(TARGET_CC)" \
		--as="$(TARGET_AS)" \
		--ar="$(TARGET_AR)" \
		--charset=UTF-8 \
		--enable-alsa \
		--disable-gui --disable-ivtv \
		--disable-decoder=apng \
		--disable-encoder=apng \
		--disable-decoder=tdsc \
		--disable-sdl \
		--disable-freetype \
		--disable-fontconfig \
		--disable-enca \
		--disable-fribidi \
		--disable-iconv \
		--disable-termcap \
		--disable-smb \
		--disable-bluray \
		--disable-libcdio \
		--disable-mencoder \
		--disable-sortsub \
		--disable-ass \
		--disable-gnutls \
		--disable-ossaudio \
		--disable-radio-v4l2 \
		--disable-tv-v4l2 \
		--disable-md5sum \
		--disable-yuv4mpeg \
		--disable-tga \
		--disable-pnm \
		--disable-xanim \
		--disable-real \
	);
endef

define Build/RunMake
	CFLAGS="$(TARGET_CPPFLAGS) $(TARGET_CFLAGS)" \
	$(MAKE) $(PKG_JOBS) -C $(PKG_BUILD_DIR)/$(1) \
		$(TARGET_CONFIGURE_OPTS) \
		$(DRIVER_MAKEOPTS) \
		LIBS="$(TARGET_LDFLAGS)" \
		LIBS_c="$(TARGET_LDFLAGS_C)" \
		BCHECK= \
		$(2)
endef

define Package/mplayer/install
	$(INSTALL_DIR) \
		$(1)/usr/bin \
		$(1)/etc

	$(INSTALL_BIN) \
		$(PKG_BUILD_DIR)/mplayer \
		$(1)/usr/bin/mplayer
	#$(INSTALL_DATA) \
	#	$(FILES_DIR)/mplayer.conf \
	#	$(1)/etc/

endef

$(eval $(call BuildPackage,mplayer))
