
/* Alango VCP8 Acoustic Configuration Profile                                 */
/*                                                                            */
/* -------------------------------------------------------------------------- */
/* This file is generated by VCP Configurator tool.  It is not recommended to */
/* introduce any manual changes into this file. Use VCP Configurator instead! */
/* -------------------------------------------------------------------------- */
/* Profile definitions for VCP8                                               */
/* Profile version: 52                                                        */
/* Created by VCP8-config revision: 18050817/1466                             */

#include "spf-postapi-vcp.h"

static vcp_profile_general_t p_gen = { /*** General profile */
  0x0034,  /*                  VER = 52           VCP profile version [int] */
  0x3e80,  /*                  FSF = 16000        Sampling frequency [Hz] [int] */
             /* FLAGS: value == 0x0001 */
  (1 << 0) , /*          VCP_LIGHT = On           VCP build version */
  0x0080,  /*                FRLEN = 128          Processing frame length [smpl] [int] */
  0x1f40,  /*                  LPF = 8000         Last Processing frequency [Hz] [int] */
  0x0800,  /*                TX_IG = 0            TX digital input gain applied right at input [dB] [dB] */
  0x0800,  /*                RX_IG = 0            RX digital input gain applied right at input [dB] [dB] */
  0x0800,  /*                TX_OG = 0            TX digital output gain applied right at output [dB] [dB] */
  0x0800,  /*                RX_OG = 0            RX digital output gain applied right at output [dB] [dB] */
  0x0000,  /*                  STG = -96          Side Tone Gain [dB] [dB] */
  0x0000,  /*                  RPD = 0.0          Reference to primary delay [ms] [flt] */
  0x02d1,  /*          TX_REFG_NOM = 9            Nominal gain for the AEC Reference signal [dB] [dB] */
  0x63ff,  /*          TX_REFG_MAX = 40           Maximal gain for the AEC Reference signal [dB] [dB] */
  0x0100,  /*          TX_VVOL_NOM = 0            Virtual volume level corresponding to the nominal reference gain [dB] [dB] */
  0x0100,  /*              TX_VVOL = 0            Current virtual volume level [dB] [dB] */
  0x7fff,  /*              TX_GMNR = 0            TX Global Maximal Noise Reduction [dB] [dB] */
  0x7fff,  /*              RX_GMNR = 0            RX Global Maximal Noise Reduction [dB] [dB] */
  0x1aa0,  /*                 DATE = 0x1aa0       DAYS since 1st Jan 2000 */
  0x023f,  /*                 TIME = 0x023f       MINUTES since 00:00 */
  0x3842,  /*                  CRC = 0x3842       CRC for all parameters [CRC is normally HEX] */
}; /**** static vcp_profile_general_t p_gen */

static vcp_profile_ns2_t p_tx_ns2 = { /*** TX NS2 */
  0x0001,  /*           TX_NS2_BPS = Bypass_proc     TX NS bypass options */
  0x0000,  /*           TX_NS2_FPF = 0            First (bottom) processed frequency [Hz] [int] */
  0x1f40,  /*           TX_NS2_LPF = 8000         Last (top) processed frequency [Hz] [int] */
  0x0dac,  /*           TX_NS2_HRF = 3500         High resolution upper frequency [Hz] [int] */
  0xfffa,  /*           TX_NS2_SNS = -6           Stationary noise suppression gain [dB] [int] */
  0xffa0,  /*          TX_NS2_MING = -96          Minimal allowed total noise suppression gain [dB] [int] */
  0x0000,  /*         TX_NS2_WBNGG = 0            Wideband noise gate gain [dB] [int] */
  0x0000,  /*            TX_NS2_TC = 0            Tone control threshold (> 0 - suppression, < 0 - attenuation), [dB] [int] */
  0xfff7,  /*          TX_NS2_GDNR = -9           Minimal allowed AGC-depended NR gain auto-correction [dB] [int] */
  0xfff4,  /*      TX_NS2_BNL_MING = -12          Minimal allowed NR gain correction by BNL [dB] [int] */
  0x0006,  /*        TX_NS2_BNL_EF = 6            BNL spectrum curvature factor (lower -> more flat) [dB] [int] */
  0x0000,  /*       TX_NS2_BNL_HIT = 0            BNL high threshold (subband NR gain increases above it) [dB] [int] */
  0x5fff,  /*       TX_NS2_BNL_HIS = 0.7500       BNL high threshold slope [frac] [flt] */
  0xffa0,  /*       TX_NS2_BNL_LOT = -96          BNL low threshold (subband NR gain is 0 dB below it) [dB] [int] */
  0x3fff,  /*       TX_NS2_BNL_LOS = 0.5000       BNL low threshold slope [frac] [flt] */
  0x02bc,  /*          TX_NS2_SNAT = 700          Stationary noise adaptation time [ms] [int] */
  0x0064,  /*          TX_NS2_TNAT = 100          Transient noise adaptation time [ms] [int] */
  0x0bb8,  /*          TX_NS2_SPAT = 3000         Speech noise adaptation time [ms] [int] */
  0x0000,  /*          TX_NS2_NTF1 = 0.0          Sensitivity to signal at low frequencies [frac] [flt] */
  0x0000,  /*          TX_NS2_NTF2 = 0.0          Sensitivity to signal at high frequencies [frac] [flt] */
  0xfffa,  /*          TX_NS2_LFNF = -6           Low frequency noise flattering minimal gain [dB] [int] */
  0x3fff,  /*           TX_NS2_NSS = 0.5000       NS smoothness [frac] [flt] */
  0x0000,  /*           TX_NS2_LAT = 0            NS look ahead time, frames [int] [int] */
             /* FLAGS: value == 0x0000 */
  (0 << 0) , /*    TX_NS2_WNR_FLAG = Off          Single-channel Wind Noise Reduction (WNR) [flag] */
  0x7fff,  /*       TX_NS2_WNR_STR = 1.00         Wind noise reduction strength [frac] [flt] */
  0xffe8,  /*      TX_NS2_WNR_MATT = -24          Wind noise reduction minimal attenuation [dB] [int] */
  0xffce,  /*       TX_NS2_WNR_THR = -50          Wind noise reduction threshold [dB] [int] */
  0x05dc,  /*        TX_NS2_WNR_IT = 1500         Wind confirmation increase time, ms [int] [int] */
  0x1770,  /*        TX_NS2_WNR_DT = 6000         Wind confirmation decrease time, ms [int] [int] */
  0x0000,  /*      TX_NS2_CNG_MODE = 0            Comfort noise generation work mode 0,1,2 [int] [int] */
  0x7332,  /*      TX_NS2_CNG_CUTG = 0.9000       Comfort noise generation gain cut level [frac] [flt] */
}; /**** static vcp_profile_ns2_t p_tx_ns2 */

static vcp_profile_eq_t p_tx_ns2_snsg_eq = { /*** TX SNS EQ */
  0x0000,   /* Num entries = 0 */
  0x0000,   /*     EQ type = 0 */
  {
   0x0000, 0x0000    /*     0.00 Hz -> -72.0 dB */
  }
}; /**** static vcp_profile_eq_t p_tx_ns2_snsg_eq */

static vcp_profile_eq_t p_tx_ns2_bnlh_eq = { /*** TX BNLH EQ */
  0x0000,   /* Num entries = 0 */
  0x0000,   /*     EQ type = 0 */
  {
   0x0000, 0x0000    /*     0.00 Hz -> -72.0 dB */
  }
}; /**** static vcp_profile_eq_t p_tx_ns2_bnlh_eq */

static vcp_profile_eq_t p_tx_ns2_ming_eq = { /*** TX MING EQ */
  0x0000,   /* Num entries = 0 */
  0x0000,   /*     EQ type = 0 */
  {
   0x0000, 0x0000    /*     0.00 Hz -> -72.0 dB */
  }
}; /**** static vcp_profile_eq_t p_tx_ns2_ming_eq */

static vcp_profile_agc_t p_tx_agc = { /*** TX AGC/DRC */
  0x0000,  /*           TX_DRC_BPS = Normal       Bypass modes */
  0x0100,  /*          TX_DRC1_SAT = 0            TX DRC1 saturation (limiting) level (SAT < 0 dB) or const gain (SAT > 0 dB) [dB] [dB] */
  0x0ccd,  /*           TX_DRC1_SL = -20          TX DRC1 input 'signal' level [dB] [dB] */
  0x0021,  /*           TX_DRC1_NL = -60          TX DRC1 input 'noise' level [dB] [dB] */
  0x0100,  /*           TX_DRC1_NG = 0            TX DRC1 noise gain [dB] [dB] */
  0x0100,  /*          TX_DRC2_SAT = 0            TX DRC2 saturation (limiting) level (SAT < 0 dB) or const gain (SAT > 0 dB) [dB] [dB] */
  0x0a00,  /*           TX_AGC_MXG = 20           TX AGC max gain [dB] [dB] */
  0x0518,  /*          TX_AGC_MXGL = -28          TX AGC signal level at which max gain is applied [dB] [dB] */
  0x5a9d,  /*           TX_AGC_ZGL = -3           TX AGC signal level at which zero gain is applied [dB] [dB] */
  0x00c8,  /*            TX_AGC_RT = 200          TX AGC 'release time', i.e. time that it takes to double the gain of voiced signal [ms] [int] */
  0x0000,  /*          TX_AGC_LTHR = -96          TX AGC trigger signal level threshold [dB] [dB] */
  0x2000,  /*          TX_AGC_VTHR = 0.2500       TX AGC VAD level threshold [frac] [flt] */
  0x7148,  /*            TX_AGC_FT = 29000        TX AGC 'fade time', i.e. time that it takes for the gain to fall by half [ms] [int] */
}; /**** static vcp_profile_agc_t p_tx_agc */

static vcp_profile_af_t p_tx_af = { /*** TX AF */
  0x0000,  /*            TX_AF_BPS = Normal       TX AF bypass options */
  0x1f40,  /*            TX_AF_UDF = 8000         Upper duplex (filtering) frequency [Hz] [int] */
  0x03e8,  /*           TX_AF_AFUF = 1000         1st adaptive filter upper frequency [Hz] [int] */
  0x0021,  /*         TX_AF_AFATHR = -60          Minimal signal level for AF adaptation [dB] [dB] */
  0x0021,  /*         TX_AF_AFFTHR = -60          Minimal signal level for AF filtering [dB] [dB] */
  0x0000,  /*            TX_AF_BFF = 0            Bottom filter frequency [Hz] [int] */
             /* FLAGS: value == 0x0001 */
  (1 << 0) , /*        TX_AF_AFCCA = On           Adaptive filter correlation-controlled adaptation [flag] */
  0x7fff,  /*          TX_AF_FLCFV = 1.00         Correlation function value limit [frac] [flt] */
             /* FLAGS: value == 0x0000 */
  (0 << 0) , /*         TX_AF_AFST = Off          Stereo AF mode (stereo AEC) [flag] */
  0x0002,  /*           TX_AF_AFAM = simple       Adaptive filter adaptation mode */
  0x7332,  /*            TX_AF_ARF = 0.9000       Adaptation rate factor [frac] [flt] */
             /* FLAGS: value == 0x0000 */
  (0 << 0) , /*         TX_AF_AFAH = Off          Reference activity hold [flag] */
  0x0064,  /*           TX_AF_AFL1 = 100          Effective length of 1st adaptive filter [ms] [int] */
             /* FLAGS: value == 0x0001 */
  (1 << 0) , /*         TX_AF_TSF1 = On           Two stage adaptive filtering of AFL1 [flag] */
  0x0064,  /*           TX_AF_AFL2 = 100          Effective length of 2nd adaptive filter (above AFUF) [ms] [int] */
             /* FLAGS: value == 0x0001 */
  (1 << 0) , /*         TX_AF_TSF2 = On           Two stage adaptive filtering of AFL2 [flag] */
             /* FLAGS: value == 0x0000 */
  (0 << 0) , /*         TX_AF_FOST = Off          Filter output sample type, off=min, on=last [flag] */
}; /**** static vcp_profile_af_t p_tx_af */

static vcp_profile_debug_t p_deb = { /*** Debugs */
  0x0000,  /*        DEB_TXIN_MODE = normal       TXin debug modes */
  0x0032,  /*        DEB_TXIN_FREQ = 50           TXin tone freq [Hz] [int] */
  0x4026,  /*        DEB_TXIN_AMPL = -6           TXin ampl FS [dB] [dB] */
  0x7fff,  /*       DEB_TXIN_DECAY = 0            TXin decay per cycle [dB] [dB] */
             /* FLAGS: value == 0x0000 */
  (0 << 0) | /*     DEB_TXIN_PAUSE = 0            TXin signal pause in frames [int] */
  (0 << 8) , /*       DEB_TXIN_LEN = 0            TXin signal length in frames [int] */
  0x0000,  /*       DEB_TXOUT_MODE = normal       TXout debug modes */
  0x0032,  /*       DEB_TXOUT_FREQ = 50           TXout debug tone freq [Hz] [int] */
  0x4026,  /*       DEB_TXOUT_AMPL = -6           TXout ampl FS [dB] [dB] */
  0x7fff,  /*      DEB_TXOUT_DECAY = 0            TXout decay per cycle [dB] [dB] */
             /* FLAGS: value == 0x0000 */
  (0 << 0) | /*    DEB_TXOUT_PAUSE = 0            TXout signal pause in frames [int] */
  (0 << 8) , /*      DEB_TXOUT_LEN = 0            TXout signal length  in frames [int] */
  0x0000,  /*        DEB_RXIN_MODE = normal       RXin debug modes */
  0x0032,  /*        DEB_RXIN_FREQ = 50           RXin debug tone freq [Hz] [int] */
  0x4026,  /*        DEB_RXIN_AMPL = -6           RXin ampl FS [dB] [dB] */
  0x7fff,  /*       DEB_RXIN_DECAY = 0            RXin decay per cycle [dB] [dB] */
             /* FLAGS: value == 0x0000 */
  (0 << 0) | /*     DEB_RXIN_PAUSE = 0            RXin signal pause in frames [int] */
  (0 << 8) , /*       DEB_RXIN_LEN = 0            RXin signal length in frames [int] */
  0x0007,  /*       DEB_RXOUT_MODE = bypass       RXout debug modes */
  0x0032,  /*       DEB_RXOUT_FREQ = 50           RXout debug tone freq [Hz] [int] */
  0x4026,  /*       DEB_RXOUT_AMPL = -6           RXout ampl FS [dB] [dB] */
  0x7fff,  /*      DEB_RXOUT_DECAY = 0            RXout decay per cycle [dB] [dB] */
             /* FLAGS: value == 0x0000 */
  (0 << 0) | /*    DEB_RXOUT_PAUSE = 0            RXout signal pause in frames [int] */
  (0 << 8) , /*      DEB_RXOUT_LEN = 0            RXout signal length  in frames [int] */
  0x7fff,  /*          DEB_TX_ISOT = 0            TX input overload threshold [dB] [dB] */
  0x01f4,  /*           DEB_TX_OSL = 500          On TX input overload emergency signal length [ms] [int] */
  0x7fff,  /*           DEB_TX_OSA = 0            On TX input overload emergency signal amplitude [dB] [dB] */
  0x02ee,  /*           DEB_TX_OSF = 750          On TX input overload emergency signal frequency [Hz] [int] */
  0x7fff,  /*          DEB_RX_ISOT = 0            RX input overload threshold [dB] [dB] */
  0x01f4,  /*           DEB_RX_OSL = 500          On RX input overload emergency signal length [ms] [int] */
  0x7fff,  /*           DEB_RX_OSA = 0            On RX input overload emergency signal amplitude [dB] [dB] */
  0x05dc,  /*           DEB_RX_OSF = 1500         On RX input overload emergency signal frequency [Hz] [int] */
}; /**** static vcp_profile_debug_t p_deb */

PROFILE_TYPE(t) profile = { 
  &p_gen,              /* General profile is always included             */
  &p_tx_ns2,           /* TX NS2                                         */
  &p_tx_ns2_snsg_eq,   /* TX SNS EQ                                      */
  &p_tx_ns2_bnlh_eq,   /* TX BNLH EQ                                     */
  &p_tx_ns2_ming_eq,   /* TX MING EQ                                     */
  0,                   /* Block [TX FS] -- IS TURNED OFF!                */
  0,                   /* Block [TX EQ] -- IS TURNED OFF!                */
  &p_tx_agc,           /* TX AGC/DRC                                     */
  0,                   /* Block [TX DC removal] -- IS TURNED OFF!        */
  0,                   /* Block [RX DC removal] -- IS TURNED OFF!        */
  0,                   /* Block [RX NS2] -- IS TURNED OFF!               */
  0,                   /* Block [RX SNS EQ] -- IS TURNED OFF!            */
  0,                   /* Block [RX BNLH EQ] -- IS TURNED OFF!           */
  0,                   /* Block [RX MING EQ] -- IS TURNED OFF!           */
  0,                   /* Block [RX FS] -- IS TURNED OFF!                */
  &p_tx_af,            /* TX AF                                          */
  0,                   /* Block [TX ES] -- IS TURNED OFF!                */
  0,                   /* Block [BCT EQ] -- IS TURNED OFF!               */
  0,                   /* Block [GCT EQ] -- IS TURNED OFF!               */
  0,                   /* Block [RX EQ] -- IS TURNED OFF!                */
  0,                   /* Block [RX AGC/DRC] -- IS TURNED OFF!           */
  0,                   /* Block [RX DTGC] -- IS TURNED OFF!              */
  0,                   /* Block [TX MIXER] -- IS TURNED OFF!             */
  0,                   /* Block [AUX DATA] -- IS TURNED OFF!             */
  0,                   /* Block [ADM] -- IS TURNED OFF!                  */
  &p_deb,              /* Debugs                                         */
  0                    /* Block [Logger] -- IS TURNED OFF!               */
}; /* PROFILE_TYPE(t) profile */

/*
###########################################
### CMDLINE0052v8R
###########################################

#
# General profile [PROFILE_TYPE(general_t)]
#
VER=52 FSF=16000 VCP_LIGHT=On FRLEN=128 LPF=8000 TX_IG=0 RX_IG=0 
  TX_OG=0 RX_OG=0 STG=-96 RPD=0.0 TX_REFG_NOM=9 TX_REFG_MAX=40 TX_VVOL_NOM=0 
  TX_VVOL=0 TX_GMNR=0 RX_GMNR=0 
# Informative -- DATE=2018/08/30 
# Informative -- TIME=09:35 
# Informative -- CRC=0x3842 

#
# Block TX_NS2_BLOCK [vcp_profile_ns2_t] is enabled
#
TX_NS2_BLOCK=On
  TX_NS2_BPS=Bypass_proc TX_NS2_FPF=0 TX_NS2_HRF=3500 TX_NS2_LAT=0 TX_NS2_LPF=8000 
  TX_NS2_SNS=-6 TX_NS2_WBNGG=0 TX_NS2_LFNF=-6 TX_NS2_MING=-96 TX_NS2_GDNR=-9 
  TX_NS2_BNL_HIT=0 TX_NS2_BNL_HIS=0.7500 TX_NS2_BNL_LOT=-96 TX_NS2_BNL_LOS=0.5000 
  TX_NS2_BNL_MING=-12 TX_NS2_BNL_EF=6 TX_NS2_SNAT=700 TX_NS2_TNAT=100 
  TX_NS2_SPAT=3000 TX_NS2_NTF1=0.0 TX_NS2_NTF2=0.0 TX_NS2_NSS=0.5000 TX_NS2_WNR_FLAG=Off 
  TX_NS2_WNR_STR=1.0000 TX_NS2_WNR_MATT=-24 TX_NS2_WNR_THR=-50 TX_NS2_WNR_IT=1500 
  TX_NS2_WNR_DT=6000 TX_NS2_CNG_CUTG=0.9000 TX_NS2_CNG_MODE=0 TX_NS2_TC=0 
  

#
# Block TX_SNS_EQ [vcp_profile_eq_t] is enabled
#
TX_SNS_EQ=On
  TX_NS2_SNS_EQ={ # Values are F1=k1; F2=k1; ... Range -inf .. +24dB. Total 0 points defined.
           
         }


#
# Block TX_BNLH_EQ [vcp_profile_eq_t] is enabled
#
TX_BNLH_EQ=On
  TX_NS2_BNLH_EQ={ # Values are F1=k1; F2=k1; ... Range -inf .. +24dB. Total 0 points defined.
           
         }


#
# Block TX_MING_EQ [vcp_profile_eq_t] is enabled
#
TX_MING_EQ=On
  TX_NS2_MING_EQ={ # Values are F1=k1; F2=k1; ... Range -inf .. +24dB. Total 0 points defined.
           
         }


#
# Block TX_OUT_AGC_BLOCK [vcp_profile_agc_t] is enabled
#
TX_OUT_AGC_BLOCK=On
  TX_DRC_BPS=Normal TX_DRC1_SAT=0 TX_DRC1_SL=-20 TX_DRC1_NL=-60 TX_DRC1_NG=0 
  TX_AGC_MXG=20 TX_AGC_MXGL=-28 TX_AGC_ZGL=-3 TX_AGC_LTHR=-96 TX_AGC_VTHR=0.2500 
  TX_AGC_RT=200 TX_AGC_FT=29000 TX_DRC2_SAT=0 

#
# Block TX_AF_BLOCK [vcp_profile_af_t] is enabled
#
TX_AF_BLOCK=On
  TX_AF_BPS=Normal TX_AF_BFF=0 TX_AF_UDF=8000 TX_AF_AFUF=1000 TX_AF_AFATHR=-60 
  TX_AF_AFFTHR=-60 TX_AF_AFST=Off TX_AF_AFAM=simple TX_AF_ARF=0.9000 TX_AF_AFAH=Off 
  TX_AF_AFCCA=On TX_AF_FLCFV=1.0000 TX_AF_AFL1=100 TX_AF_TSF1=On TX_AF_AFL2=100 
  TX_AF_TSF2=On TX_AF_FOST=Off 

#
# Block DEBUG_BLOCK [vcp_profile_debug_t] is enabled
#
DEBUG_BLOCK=On
  DEB_TXIN_MODE=normal DEB_TXIN_FREQ=50 DEB_TXIN_AMPL=-6 DEB_TXIN_DECAY=0 
  DEB_TXIN_LEN=0 DEB_TXIN_PAUSE=0 DEB_TXOUT_MODE=normal DEB_TXOUT_FREQ=50 DEB_TXOUT_AMPL=-6 
  DEB_TXOUT_DECAY=0 DEB_TXOUT_LEN=0 DEB_TXOUT_PAUSE=0 DEB_RXIN_MODE=normal DEB_RXIN_FREQ=50 
  DEB_RXIN_AMPL=-6 DEB_RXIN_DECAY=0 DEB_RXIN_LEN=0 DEB_RXIN_PAUSE=0 DEB_RXOUT_MODE=bypass DEB_RXOUT_FREQ=50 
  DEB_RXOUT_AMPL=-6 DEB_RXOUT_DECAY=0 DEB_RXOUT_LEN=0 DEB_RXOUT_PAUSE=0 
  DEB_TX_ISOT=0 DEB_TX_OSL=500 DEB_TX_OSA=0 DEB_TX_OSF=750 DEB_RX_ISOT=0 
  DEB_RX_OSL=500 DEB_RX_OSA=0 DEB_RX_OSF=1500 



*/
