#
#	Copyright (c) 2013, 2017	Montage Inc.	All rights reserved. 
#
# Kernel API
obj-$(CONFIG_PANTHER) += kernel/

obj-$(CONFIG_PANTHER) += base/

# Ethernet
obj-$(CONFIG_PANTHER_ETH) += ethernet/

#WiFi
obj-$(CONFIG_PANTHER_WLAN) += wlan/

#SDHCI
#obj-$(CONFIG_PANTHER_SDHCI) += mmc/

#Sound
obj-$(CONFIG_PANTHER_SND) += sound/

# Software UART
obj-$(CONFIG_PANTHER_SOFTWARE_UART) += uart/

#obj-$(CONFIG_EARLY_PRINTK)	+=

#EXTRA_CFLAGS += -Werror
#
# 	Uncomment to use Switch Port0 as WAN port
#
#EXTRA_CFLAGS += -DCML_WAN_P0
