#
# Copyright (C) 2014 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#
export WIFIAUDIO_MONTAGE=y
#export WIFIAUDIO_MTK=y

include $(TOPDIR)/rules.mk

PKG_NAME:=lenovocgi
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/lenovocgi
  SECTION:=sound
  CATEGORY:=Sound
  TITLE:=postplaylist
  DEPENDS:= +libjson-c +libcurl +libuci +libcdb
endef

define Package/lenovocgi/description
  post music cgi
endef

define Build/Compile
	CC="$(TARGET_CC)" \
	CFLAGS="$(TARGET_CFLAGS) -I$(STAGING_DIR)/usr/include/json-c -I$(STAGING_DIR)/usr/include" \
	LDFLAGS="$(TARGET_LDFLAGS) -L$(STAGING_DIR)/usr/lib -Wl,-rpath-link=$(STAGING_DIR)/usr/lib" \
	$(MAKE) -C $(PKG_BUILD_DIR) \
		all
endef

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
	$(CP) ./src/* $(PKG_BUILD_DIR)/
endef

define Package/lenovocgi/install
	$(INSTALL_DIR) $(1)/www/cgi-bin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/provision/*.cgi $(1)/www/cgi-bin
endef

$(eval $(call BuildPackage,lenovocgi))
