#!/bin/sh /etc/rc.common
# Copyright (C) 2013 Montage Inc.

START=15

local CRON_PROG="crond"
local CRONFILE="/etc/crontabs/root"

start() {
        $CRON_PROG
}

stop() {
        start-stop-daemon -K -skill -x$CRON_PROG
}
